spring:
  application:
    name: jpql
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:/Users/apoorvatech/apoorva/projects/spring-boot/jpql/src/main/resources/testdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE  # File-based H2 database
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
        maximum-pool-size: 10  # Optional: Pool size configuration
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
